/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchPlotRouteImport } from './routes/search-plot'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PasskeyRouteImport } from './routes/passkey'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as CodewordRouteImport } from './routes/codeword'
import { Route as IndexRouteImport } from './routes/index'

const SearchPlotRoute = SearchPlotRouteImport.update({
  id: '/search-plot',
  path: '/search-plot',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PasskeyRoute = PasskeyRouteImport.update({
  id: '/passkey',
  path: '/passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const CodewordRoute = CodewordRouteImport.update({
  id: '/codeword',
  path: '/codeword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codeword': typeof CodewordRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/passkey': typeof PasskeyRoute
  '/search': typeof SearchRoute
  '/search-plot': typeof SearchPlotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codeword': typeof CodewordRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/passkey': typeof PasskeyRoute
  '/search': typeof SearchRoute
  '/search-plot': typeof SearchPlotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codeword': typeof CodewordRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/passkey': typeof PasskeyRoute
  '/search': typeof SearchRoute
  '/search-plot': typeof SearchPlotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codeword'
    | '/entry'
    | '/login'
    | '/overview'
    | '/passkey'
    | '/search'
    | '/search-plot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codeword'
    | '/entry'
    | '/login'
    | '/overview'
    | '/passkey'
    | '/search'
    | '/search-plot'
  id:
    | '__root__'
    | '/'
    | '/codeword'
    | '/entry'
    | '/login'
    | '/overview'
    | '/passkey'
    | '/search'
    | '/search-plot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodewordRoute: typeof CodewordRoute
  EntryRoute: typeof EntryRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PasskeyRoute: typeof PasskeyRoute
  SearchRoute: typeof SearchRoute
  SearchPlotRoute: typeof SearchPlotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search-plot': {
      id: '/search-plot'
      path: '/search-plot'
      fullPath: '/search-plot'
      preLoaderRoute: typeof SearchPlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passkey': {
      id: '/passkey'
      path: '/passkey'
      fullPath: '/passkey'
      preLoaderRoute: typeof PasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeword': {
      id: '/codeword'
      path: '/codeword'
      fullPath: '/codeword'
      preLoaderRoute: typeof CodewordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodewordRoute: CodewordRoute,
  EntryRoute: EntryRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PasskeyRoute: PasskeyRoute,
  SearchRoute: SearchRoute,
  SearchPlotRoute: SearchPlotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
