/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchPlotImport } from './routes/search-plot'
import { Route as SearchImport } from './routes/search'
import { Route as OverviewImport } from './routes/overview'
import { Route as LoginImport } from './routes/login'
import { Route as EntryImport } from './routes/entry'
import { Route as CodewordImport } from './routes/codeword'
import { Route as BioauthImport } from './routes/bioauth'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SearchPlotRoute = SearchPlotImport.update({
  id: '/search-plot',
  path: '/search-plot',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const OverviewRoute = OverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const EntryRoute = EntryImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRoute,
} as any)

const CodewordRoute = CodewordImport.update({
  id: '/codeword',
  path: '/codeword',
  getParentRoute: () => rootRoute,
} as any)

const BioauthRoute = BioauthImport.update({
  id: '/bioauth',
  path: '/bioauth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bioauth': {
      id: '/bioauth'
      path: '/bioauth'
      fullPath: '/bioauth'
      preLoaderRoute: typeof BioauthImport
      parentRoute: typeof rootRoute
    }
    '/codeword': {
      id: '/codeword'
      path: '/codeword'
      fullPath: '/codeword'
      preLoaderRoute: typeof CodewordImport
      parentRoute: typeof rootRoute
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/search-plot': {
      id: '/search-plot'
      path: '/search-plot'
      fullPath: '/search-plot'
      preLoaderRoute: typeof SearchPlotImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bioauth': typeof BioauthRoute
  '/codeword': typeof CodewordRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/search': typeof SearchRoute
  '/search-plot': typeof SearchPlotRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bioauth': typeof BioauthRoute
  '/codeword': typeof CodewordRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/search': typeof SearchRoute
  '/search-plot': typeof SearchPlotRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bioauth': typeof BioauthRoute
  '/codeword': typeof CodewordRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/search': typeof SearchRoute
  '/search-plot': typeof SearchPlotRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bioauth'
    | '/codeword'
    | '/entry'
    | '/login'
    | '/overview'
    | '/search'
    | '/search-plot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bioauth'
    | '/codeword'
    | '/entry'
    | '/login'
    | '/overview'
    | '/search'
    | '/search-plot'
  id:
    | '__root__'
    | '/'
    | '/bioauth'
    | '/codeword'
    | '/entry'
    | '/login'
    | '/overview'
    | '/search'
    | '/search-plot'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BioauthRoute: typeof BioauthRoute
  CodewordRoute: typeof CodewordRoute
  EntryRoute: typeof EntryRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  SearchRoute: typeof SearchRoute
  SearchPlotRoute: typeof SearchPlotRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BioauthRoute: BioauthRoute,
  CodewordRoute: CodewordRoute,
  EntryRoute: EntryRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  SearchRoute: SearchRoute,
  SearchPlotRoute: SearchPlotRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bioauth",
        "/codeword",
        "/entry",
        "/login",
        "/overview",
        "/search",
        "/search-plot"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bioauth": {
      "filePath": "bioauth.tsx"
    },
    "/codeword": {
      "filePath": "codeword.tsx"
    },
    "/entry": {
      "filePath": "entry.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/overview": {
      "filePath": "overview.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/search-plot": {
      "filePath": "search-plot.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
